name: Release SDK

on:
  push:
    tags:
      - '*.*.*'
      - '*.*.*-SNAPSHOT'

jobs:
  publish:
    name: Publish to Maven Central
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Publish to Maven Central
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        run: >
          ./gradlew :ads:publish
          -PsdkVersion=${{ steps.get_version.outputs.VERSION }}
          -PmavenCentralUsername="$MAVEN_USERNAME"
          -PmavenCentralPassword="$MAVEN_PASSWORD"
          -Psigning.key="$SIGNING_KEY"
          -Psigning.password="$SIGNING_PASSWORD"